apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: cf
  name: noam-rollout-reporter
  namespace: aws-local-runtime
spec:
  dependencies:
  - eventName: rollouts
    eventSourceName: noam-rollout-reporter
    name: rollouts
  - eventName: replicasets
    eventSourceName: noam-rollout-reporter
    name: replicasets
  - eventName: analysisruns
    eventSourceName: noam-rollout-reporter
    name: analysisruns
  eventBusName: codefresh-eventbus
  template:
    container:
      name: ''
      resources: {}
  triggers:
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: rollouts
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data.object
          src:
            dataKey: body
            dependencyName: rollouts
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://philipp-platform.ngrok.io/2.0/api/events
      name: rollouts
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: replicasets
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data.object
          src:
            dataKey: body
            dependencyName: replicasets
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://philipp-platform.ngrok.io/2.0/api/events
      name: replicasets
  - retryStrategy:
      duration: 0
      steps: 3
    template:
      conditions: analysisruns
      http:
        headers:
          Content-Type: application/json
        method: POST
        payload:
        - dest: data.object
          src:
            dataKey: body
            dependencyName: analysisruns
        secureHeaders:
        - name: Authorization
          valueFrom:
            secretKeyRef:
              key: token
              name: codefresh-token
        url: https://philipp-platform.ngrok.io/2.0/api/events
      name: analysisruns
status: {}
