apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    codefresh.io/entity: internal-config
    codefresh.io/internal: "true"
  name: in-cluster
spec:
  destination:
    namespace: aws-local-runtime
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      include: '{all-runtimes-all-clusters/*.yaml,all-runtimes-all-clusters/**/*.yaml,runtimes/aws-local-runtime/*.yaml,runtimes/aws-local-runtime/**/*.yaml,control-planes/*.yaml,control-planes/**/*.yaml}'
      recurse: true
    path: shared-config/resources
    repoURL: https://github.com/PhilippPlotnikov/aws-local-runtime.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
    - allowEmpty=true
